In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
m1=np.random.randn(5,5)
m2=np.random.randn(5,5)


In [4]:
print(m1+m2)

[[-2.74102717 -0.12145736  1.43392156  0.31674642 -1.01916201]
 [ 1.00007505  1.32169227 -1.21007418 -2.47671122 -0.83699162]
 [-1.44049317  0.88374224 -0.65390534 -2.15184972  0.94976817]
 [-0.65077225  0.45945187  1.90905428 -2.14717764  1.30825308]
 [ 2.37327813 -1.96272124  0.5644944  -1.44038002  0.84753422]]


In [5]:
m1

array([[-0.02880283, -0.45493898,  0.19585629,  0.20604642, -0.13153043],
       [ 0.79877523,  0.54102032,  1.39231356, -1.20195743, -1.27162588],
       [-0.7020536 ,  0.1562761 , -0.03006467, -0.30332283,  1.51480501],
       [-0.59005904,  0.18458563,  0.43361399, -1.28058299, -0.59812335],
       [ 1.63528468, -1.41974842,  0.43256377, -0.19585561, -0.06301906]])

In [6]:
m2

array([[-2.71222434,  0.33348162,  1.23806526,  0.11069999, -0.88763157],
       [ 0.20129982,  0.78067194, -2.60238774, -1.27475379,  0.43463425],
       [-0.73843957,  0.72746615, -0.62384067, -1.84852689, -0.56503683],
       [-0.06071321,  0.27486624,  1.47544029, -0.86659464,  1.90637643],
       [ 0.73799344, -0.54297282,  0.13193064, -1.24452441,  0.91055327]])